### ISSUE TITLE
--format isn't recognized

### ISSUE THREAD

**Issue by vitalijr2** [codacy/codacy-cli-v2-action#8]
Configuration file `.codacy/codacy.yml`
```yaml
runtimes:
  - node@22.2.0
  - java@11.0.27
tools:
  - eslint@8.57.0
  - pmd@6.55.0
  - semgrep@1.78.0
  - trivy@0.59.1
```

The Codacy CLI step:
```yaml
      - name: Run Codacy CLI
        uses: codacy/codacy-cli-v2-action@main
        with:
          project_token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          sarif_file_path: results.sarif
          upload_report: true
```

The build is failed wit message:
```log
Run echo "Running the tool"
  echo "Running the tool"
  /tmp/codacy-cli-v2 analyze -t  --format sarif -o results.sarif
  echo "Tool run complete"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/11.0.27-6/x64
    JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Zulu_jdk/11.0.27-6/x64
    COMMIT_SHA: 5d030e699d1374b0b8fbdc93002068db83d4f585
Running the tool
2025/05/29 18:47:12 Warning: Failed to load language configuration: languages configuration file not found: neither .codacy/tools-configs/languages-config.yaml nor .codacy/tools-configs/languages-config.json exists. Running all tools.
2025/05/29 18:47:12 Running tools for the specified file(s)...
2025/05/29 18:47:12 Running --format...
2025/05/29 18:47:12 Tool failed to run: --format: unsupported tool: --format
Tool run complete
Run if [ "true" == "true" ]; then
Uploading the results
sed: can't read results.sarif: No such file or directory
```
